### ISSUE TITLE
GeographicLib exception: File not readable

### ISSUE THREAD

**Issue by bertanbee** [SkyRats/mavbase2#2]
If you find the following error while launching mavbase2, there is an approach to solve that problem.

![image](https://user-images.githubusercontent.com/52827517/181124726-626c56cf-160f-492b-8b5a-c67599dcb024.png)

 Starting from a specific date, for some reason, the files of GeographicLib are not being placed in the corresponding folder /usr/share/. 
 To resolve that, you can try installing manually that library following the instructions on this link https://geographiclib.sourceforge.io/C++/doc/install.html or, just in case it doesn't work, you can force the necessary files into the desired folder (works on Linux):

 1. Download and extract the folder "geoids" from this link: https://sourceforge.net/projects/geographiclib/files/geoids-distrib/egm96-5.tar.bz2/download?use_mirror=razaoinfo
 2. Using mkdir command as superuser, create the necessary directories (/usr/share/GeographicLib/geoids)
 3. Using cp or mv command as superuser, add each one of the files from the downloaded folder to /usr/share/GeographicLib/geoids
 4. Done! Happy drone coding!

**Comment by pedro-fuoco** [comment]
Alternatively, try:
```sudo apt install libgeographic-dev geographiclib-tools```
```cd ~/skyrats_ws2/src/mavros/mavros/scripts```
```sudo ./install_geographiclib_datasets.sh```

**Comment by pedro-fuoco** [comment]
Fixed in a skyrats-workplace commit
